# Generated by Django 4.1.7 on 2023-02-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
