# Generated by Django 4.1.7 on 2023-02-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_remove_comment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
