# Generated by Django 4.1.7 on 2023-02-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
